---
abstract: 'Transport-independent implementation of json-rpc 2.0'
author:
  - 'Alex Efros  C<< <powerman-asdf@ya.ru> >>'
  - 'Alex Efros <powerman-asdf@ya.ru>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSON-RPC2
no_index:
  directory:
    - inc
    - t
recommends:
  Pod::Coverage: 0.18
  Test::CheckManifest: 0.9
  Test::Perl::Critic: 0
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
requires:
  JSON::XS: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.002001
