name: Test

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        perl:
          - '5.40'
          - '5.38'

    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - run: perl -V

      - run: cpanm --installdeps --with-configure .

      - run: perl Build.PL && ./Build && cover -test
